version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.4-jdk-11

    steps:
      - checkout

      - run:
          name: Build Maven Project
          command: mvn clean package

  
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
